#!/usr/bin/env python3
"""Expand testdata JSON scenario files to 18 scenarios each (180 total)."""
import json
from pathlib import Path

ISTQB = "https://www.istqb.org"
OWASP_AUTH = "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html"
OWASP_INPUT = "https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html"
OWASP_XSS = "https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html"

BASE = Path(__file__).resolve().parent.parent / "src" / "test" / "resources" / "testdata"


def m(case_id, desc, priority, technique, test_type, test_level, standard, reference=ISTQB):
    return {
        "caseId": case_id,
        "description": desc,
        "priority": priority,
        "technique": technique,
        "testType": test_type,
        "testLevel": test_level,
        "standard": standard,
        "reference": reference,
    }


def write(name, data):
    path = BASE / name
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"{name}: {len(data)} scenarios")


def main():
    login = [
        {**m("LGN-001", "Invalid email and invalid password", "P0", "negative-test", "regression", "system-test", "OWASP", OWASP_AUTH),
         "email": "invalid@example.com", "password": "invalid_password", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-002", "Valid email with invalid password", "P0", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "email": "known_user@example.com", "password": "wrong_password", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-003", "Invalid email with random password", "P1", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "email": "not_exists@example.com", "password": "123456", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-004", "Empty email and password", "P0", "boundary-value", "smoke", "system-test", "ISTQB"),
         "email": "", "password": "", "expectWarning": False, "expectedWarningContains": ""},
        {**m("LGN-005", "Empty email with non-empty password", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "email": "", "password": "some_password", "expectWarning": False, "expectedWarningContains": ""},
        {**m("LGN-006", "Non-empty email with empty password", "P1", "state-transition", "regression", "system-test", "ISTQB"),
         "email": "user@example.com", "password": "", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-007", "Email format without domain", "P2", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "email": "abc@", "password": "test123", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-008", "Email with leading and trailing spaces", "P2", "boundary-value", "regression", "system-test", "OWASP", OWASP_AUTH),
         "email": "  user@example.com  ", "password": "test123", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-SEC-01", "SQL injection in email and password fields", "P0", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "email": "' OR '1'='1", "password": "' OR 1=1--", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-SEC-02", "XSS payload in email field", "P1", "security", "regression", "system-test", "OWASP", OWASP_XSS),
         "email": "<script>alert(1)</script>@test.com", "password": "test123", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-SEC-03", "SQL injection in password field only", "P1", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "email": "user@example.com", "password": "admin'--", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-EP-01", "Email without @ symbol (invalid partition)", "P1", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "email": "plainemail", "password": "test123", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-EP-02", "Double @ in email address", "P2", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "email": "user@@domain.com", "password": "test123", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-BV-01", "Single character password boundary", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "email": "user@example.com", "password": "a", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-BV-02", "Very long password (128 chars) boundary", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "email": "user@example.com", "password": "x" * 128, "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-EG-01", "Common weak password guess", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "email": "admin@example.com", "password": "password123", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-EG-02", "Password field with only whitespace", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "email": "user@example.com", "password": "   ", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
        {**m("LGN-ST-01", "Failed login keeps user on login page (state)", "P1", "state-transition", "regression", "system-test", "ISTQB"),
         "email": "retry@example.com", "password": "wrongpass", "expectWarning": True,
         "expectedWarningContains": "No match for E-Mail Address and/or Password"},
    ]

    ts = "${timestamp}"
    register = [
        {**m("RGN-001", "Positive register", "P0", "state-transition", "smoke", "acceptance-test", "ISTQB"),
         "firstName": f"Test{ts}", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": True, "expectedSuccessContains": "created", "expectedWarningContains": ""},
        {**m("RGN-002", "Invalid email format", "P0", "equivalence-partitioning", "regression", "system-test", "OWASP", OWASP_AUTH),
         "firstName": f"Test{ts}", "lastName": "User", "email": "invalid-email", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "E-Mail Address"},
        {**m("RGN-003", "Empty email", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "firstName": f"Test{ts}", "lastName": "User", "email": "", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "E-Mail Address"},
        {**m("RGN-004", "Short password", "P1", "boundary-value", "regression", "system-test", "OWASP", OWASP_AUTH),
         "firstName": f"Test{ts}", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "123", "confirmPassword": "123", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "Password"},
        {**m("RGN-005", "Password and confirm password mismatch", "P1", "negative-test", "regression", "system-test", "OWASP", OWASP_AUTH),
         "firstName": f"Test{ts}", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "Test12345!", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "Password"},
        {**m("RGN-006", "Empty first name", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "firstName": "", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "First Name"},
        {**m("RGN-007", "Empty last name", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "firstName": f"Test{ts}", "lastName": "", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "Last Name"},
        {**m("RGN-008", "Empty telephone", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "firstName": f"Test{ts}", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "Telephone"},
        {**m("RGN-009", "Empty password", "P2", "boundary-value", "regression", "system-test", "OWASP", OWASP_AUTH),
         "firstName": f"Test{ts}", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "", "confirmPassword": "", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "Password"},
        {**m("RGN-010", "Subscribe newsletter true (still should validate)", "P2", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "firstName": f"Test{ts}", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": True,
         "expectSuccess": True, "expectedSuccessContains": "created", "expectedWarningContains": ""},
        {**m("RGN-SEC-01", "XSS payload in first name field", "P1", "security", "regression", "system-test", "OWASP", OWASP_XSS),
         "firstName": "<script>alert(1)</script>", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": True, "expectedSuccessContains": "created", "expectedWarningContains": ""},
        {**m("RGN-SEC-02", "SQL injection in email field", "P1", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "firstName": f"Test{ts}", "lastName": "User", "email": "admin'--@example.com", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "E-Mail Address"},
        {**m("RGN-SEC-03", "SQL injection in first name field", "P2", "security", "regression", "system-test", "OWASP", OWASP_INPUT),
         "firstName": "Robert'); DROP TABLE users;--", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": True, "expectedSuccessContains": "created", "expectedWarningContains": ""},
        {**m("RGN-EP-01", "Password without special character", "P2", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "firstName": f"Test{ts}", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "Test1234", "confirmPassword": "Test1234", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "Password"},
        {**m("RGN-BV-01", "Single character first name boundary", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "firstName": "A", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": True, "expectedSuccessContains": "created", "expectedWarningContains": ""},
        {**m("RGN-BV-02", "Minimum valid telephone (7 digits)", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "firstName": f"Test{ts}", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "1234567",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": True, "expectedSuccessContains": "created", "expectedWarningContains": ""},
        {**m("RGN-NEG-01", "Empty confirm password only", "P1", "negative-test", "regression", "system-test", "OWASP", OWASP_AUTH),
         "firstName": f"Test{ts}", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "+15551234567",
         "password": "Test1234!", "confirmPassword": "", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "Password"},
        {**m("RGN-EG-01", "Telephone with letters (user typo)", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "firstName": f"Test{ts}", "lastName": "User", "email": f"autouser+{ts}@example.com", "telephone": "abc-phone",
         "password": "Test1234!", "confirmPassword": "Test1234!", "subscribeNewsletter": False,
         "expectSuccess": False, "expectedSuccessContains": "", "expectedWarningContains": "Telephone"},
    ]

    forgot = [
        {**m("FPW-001", "Valid format; demo DB may not have user — expect server feedback", "P0", "state-transition", "smoke", "system-test", "ISTQB"),
         "email": "autouser@example.com", "expectSuccess": True, "expectedMessageContains": "not found in our records"},
        {**m("FPW-002", "Invalid email format", "P0", "negative-test", "regression", "system-test", "OWASP", OWASP_AUTH),
         "email": "invalid-email", "expectSuccess": False, "expectedMessageContains": "E-Mail Address"},
        {**m("FPW-003", "Empty email", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "email": "", "expectSuccess": False, "expectedMessageContains": "E-Mail Address"},
        {**m("FPW-004", "Non-existing but valid email", "P1", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "email": "doesnotexist@example.com", "expectSuccess": True, "expectedMessageContains": "not found in our records"},
        {**m("FPW-005", "Email with leading/trailing spaces (trimmed by site)", "P2", "boundary-value", "regression", "system-test", "OWASP", OWASP_AUTH),
         "email": "  autouser@example.com  ", "expectSuccess": True, "expectedMessageContains": "not found in our records"},
        {**m("FPW-SEC-01", "SQL injection in email field", "P0", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "email": "' OR 1=1--", "expectSuccess": False, "expectedMessageContains": "E-Mail Address"},
        {**m("FPW-SEC-02", "XSS payload in email field", "P1", "security", "regression", "system-test", "OWASP", OWASP_XSS),
         "email": "<script>alert(1)</script>@test.com", "expectSuccess": False, "expectedMessageContains": "E-Mail Address"},
        {**m("FPW-EP-01", "Email without TLD", "P1", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "email": "user@domain", "expectSuccess": False, "expectedMessageContains": "E-Mail Address"},
        {**m("FPW-EP-02", "Double dot in local part", "P2", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "email": "user..name@example.com", "expectSuccess": True, "expectedMessageContains": "not found in our records"},
        {**m("FPW-BV-01", "Minimum valid email a@b.co", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "email": "a@b.co", "expectSuccess": True, "expectedMessageContains": "not found in our records"},
        {**m("FPW-BV-02", "Very long local part (64 chars)", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "email": "a" * 64 + "@example.com", "expectSuccess": True, "expectedMessageContains": "not found in our records"},
        {**m("FPW-NEG-01", "Email with only spaces", "P1", "negative-test", "regression", "system-test", "ISTQB"),
         "email": "   ", "expectSuccess": False, "expectedMessageContains": "E-Mail Address"},
        {**m("FPW-NEG-02", "Email missing local part", "P1", "negative-test", "regression", "system-test", "ISTQB"),
         "email": "@example.com", "expectSuccess": False, "expectedMessageContains": "E-Mail Address"},
        {**m("FPW-EG-01", "Common admin email guess", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "email": "admin@admin.com", "expectSuccess": True, "expectedMessageContains": "not found in our records"},
        {**m("FPW-EG-02", "Plus-addressing email format", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "email": "user+tag@example.com", "expectSuccess": True, "expectedMessageContains": "not found in our records"},
        {**m("FPW-ST-01", "Valid email triggers forgotten password route", "P1", "state-transition", "regression", "system-test", "ISTQB"),
         "email": "reset.test@example.com", "expectSuccess": True, "expectedMessageContains": "not found in our records"},
        {**m("FPW-ST-02", "Numeric local part email", "P2", "state-transition", "regression", "system-test", "ISTQB"),
         "email": "123456@example.com", "expectSuccess": True, "expectedMessageContains": "not found in our records"},
        {**m("FPW-SEC-03", "Auth bypass attempt with null byte in email", "P2", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "email": "user%00@example.com", "expectSuccess": False, "expectedMessageContains": "E-Mail Address"},
    ]

    cart = [
        {**m("CRT-001", "Add iMac to cart from home grid", "P0", "state-transition", "smoke", "system-test", "ISTQB"),
         "productNameContains": "iMac", "expectAddSuccess": True, "expectedCartContains": "iMac"},
        {**m("CRT-002", "Add HTC product to cart from home grid", "P1", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "productNameContains": "HTC", "expectAddSuccess": True, "expectedCartContains": "HTC"},
        {**m("CRT-003", "No matching product should not be added", "P1", "negative-test", "regression", "system-test", "OWASP", OWASP_INPUT),
         "productNameContains": "zzzznonexistentproduct999", "expectAddSuccess": False, "expectedCartContains": ""},
        {**m("CRT-BV-01", "Sepete 0 adet ürün ekleme — miktar sınırı", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "cartAction": "zero_quantity_add", "productNameContains": "iMac", "cartQuantity": 0,
         "expectAddSuccess": False, "expectedCartContains": ""},
        {**m("CRT-BV-02", "Sepeti boşaltma — sepet içeriği sınır durumu", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "cartAction": "empty_cart", "productNameContains": "iMac", "expectAddSuccess": True, "expectedCartContains": ""},
        {**m("CRT-004", "Add MacBook product to cart", "P1", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "productNameContains": "MacBook", "expectAddSuccess": True, "expectedCartContains": "MacBook"},
        {**m("CRT-005", "Add Canon camera product to cart", "P1", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "productNameContains": "Canon", "expectAddSuccess": True, "expectedCartContains": "Canon"},
        {**m("CRT-006", "Add iPhone product to cart", "P2", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "productNameContains": "iPhone", "expectAddSuccess": True, "expectedCartContains": "iPhone"},
        {**m("CRT-BV-03", "Minimum quantity 1 add from product detail", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "cartAction": "zero_quantity_add", "productNameContains": "iMac", "cartQuantity": 1,
         "expectAddSuccess": True, "expectedCartContains": "iMac"},
        {**m("CRT-BV-04", "High quantity 10 add from product detail", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "cartAction": "zero_quantity_add", "productNameContains": "HTC", "cartQuantity": 10,
         "expectAddSuccess": True, "expectedCartContains": "HTC"},
        {**m("CRT-SEC-01", "XSS-like product search fragment should not add", "P1", "security", "regression", "system-test", "OWASP", OWASP_XSS),
         "productNameContains": "<script>alert(1)</script>", "expectAddSuccess": False, "expectedCartContains": ""},
        {**m("CRT-SEC-02", "SQL injection-like product search fragment", "P2", "security", "regression", "system-test", "OWASP", OWASP_INPUT),
         "productNameContains": "' OR 1=1--", "expectAddSuccess": False, "expectedCartContains": ""},
        {**m("CRT-NEG-01", "Empty product name fragment", "P1", "negative-test", "regression", "system-test", "ISTQB"),
         "productNameContains": "", "expectAddSuccess": False, "expectedCartContains": ""},
        {**m("CRT-EG-01", "Typo product name should fail", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "productNameContains": "ImacTypo999", "expectAddSuccess": False, "expectedCartContains": ""},
        {**m("CRT-EG-02", "Partial match Mac returns product", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "productNameContains": "Mac", "expectAddSuccess": True, "expectedCartContains": "Mac"},
        {**m("CRT-ST-01", "Add Samsung product state transition", "P1", "state-transition", "regression", "system-test", "ISTQB"),
         "productNameContains": "Samsung", "expectAddSuccess": True, "expectedCartContains": "Samsung"},
        {**m("CRT-ST-02", "Add Palm product then verify cart", "P2", "state-transition", "regression", "system-test", "ISTQB"),
         "productNameContains": "Palm", "expectAddSuccess": True, "expectedCartContains": "Palm"},
        {**m("CRT-NEG-02", "Special characters only product search", "P2", "negative-test", "regression", "system-test", "ISTQB"),
         "productNameContains": "!@#$%", "expectAddSuccess": False, "expectedCartContains": ""},
    ]

    checkout = [
        {**m("CHK-SEC-01", "Checkout sayfasına login olmadan erişim engellenmeli", "P1", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "requireProductInCart": False, "productNameContains": "", "expectCheckoutAccessible": False, "expectedBodyContains": ""},
        {**m("CHK-002", "Checkout should be blocked when cart is empty", "P0", "negative-test", "regression", "acceptance-test", "ISTQB"),
         "requireProductInCart": False, "productNameContains": "", "expectCheckoutAccessible": False, "expectedBodyContains": "shopping cart"},
        {**m("CHK-BV-01", "Boş sepet ile checkout sayfasına erişim engellenmeli", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "requireProductInCart": False, "productNameContains": "", "expectCheckoutAccessible": False, "expectedBodyContains": "shopping cart"},
        {**m("CHK-001", "Logged-in user with iMac in cart can reach checkout", "P0", "state-transition", "smoke", "acceptance-test", "ISTQB"),
         "requireProductInCart": True, "productNameContains": "iMac", "expectCheckoutAccessible": True, "expectedBodyContains": ""},
        {**m("CHK-003", "Logged-in user with HTC in cart can reach checkout", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "requireProductInCart": True, "productNameContains": "HTC", "expectCheckoutAccessible": True, "expectedBodyContains": ""},
        {**m("CHK-004", "Logged-in user with MacBook in cart can reach checkout", "P1", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "requireProductInCart": True, "productNameContains": "MacBook", "expectCheckoutAccessible": True, "expectedBodyContains": ""},
        {**m("CHK-005", "Logged-in user with Canon in cart can reach checkout", "P2", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "requireProductInCart": True, "productNameContains": "Canon", "expectCheckoutAccessible": True, "expectedBodyContains": ""},
        {**m("CHK-006", "Logged-in user with iPhone in cart can reach checkout", "P2", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "requireProductInCart": True, "productNameContains": "iPhone", "expectCheckoutAccessible": True, "expectedBodyContains": ""},
        {**m("CHK-NEG-01", "Empty cart after logout attempt blocked", "P1", "negative-test", "regression", "system-test", "ISTQB"),
         "requireProductInCart": False, "productNameContains": "", "expectCheckoutAccessible": False, "expectedBodyContains": ""},
        {**m("CHK-SEC-02", "Direct checkout URL without cart items", "P1", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "requireProductInCart": False, "productNameContains": "", "expectCheckoutAccessible": False, "expectedBodyContains": "shopping cart"},
        {**m("CHK-BV-02", "Single item minimum cart checkout access", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "requireProductInCart": True, "productNameContains": "iMac", "expectCheckoutAccessible": True, "expectedBodyContains": ""},
        {**m("CHK-ST-01", "Checkout flow after adding Samsung product", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "requireProductInCart": True, "productNameContains": "Samsung", "expectCheckoutAccessible": True, "expectedBodyContains": ""},
        {**m("CHK-ST-02", "Checkout flow after adding Palm product", "P2", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "requireProductInCart": True, "productNameContains": "Palm", "expectCheckoutAccessible": True, "expectedBodyContains": ""},
        {**m("CHK-EG-01", "Checkout attempt without adding product (user error)", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "requireProductInCart": False, "productNameContains": "", "expectCheckoutAccessible": False, "expectedBodyContains": "shopping cart"},
        {**m("CHK-EP-01", "Valid product partition MacBook Air checkout", "P2", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "requireProductInCart": True, "productNameContains": "MacBook Air", "expectCheckoutAccessible": True, "expectedBodyContains": ""},
        {**m("CHK-NEG-02", "Checkout blocked when cart is empty (special chars scenario)", "P1", "negative-test", "regression", "system-test", "ISTQB"),
         "requireProductInCart": False, "productNameContains": "", "expectCheckoutAccessible": False, "expectedBodyContains": "shopping cart"},
        {**m("CHK-SEC-03", "Checkout cart page should not expose sensitive data", "P2", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "requireProductInCart": False, "productNameContains": "", "expectCheckoutAccessible": False, "expectedBodyContains": ""},
        {**m("CHK-BV-03", "Boundary: checkout with Sony product in cart", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "requireProductInCart": True, "productNameContains": "Sony", "expectCheckoutAccessible": True, "expectedBodyContains": ""},
    ]

    search = [
        {**m("SCH-001", "Known product keyword returns results", "P0", "equivalence-partitioning", "smoke", "system-test", "ISTQB"),
         "query": "iMac", "expectSearchRoute": True, "expectProductResults": True, "expectedBodyContains": "iMac"},
        {**m("SCH-002", "Another valid keyword", "P1", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "query": "HTC", "expectSearchRoute": True, "expectProductResults": True, "expectedBodyContains": "HTC"},
        {**m("SCH-003", "No-match query (boundary / negative)", "P1", "negative-test", "regression", "system-test", "ISTQB"),
         "query": "zzzznonexistentproduct999", "expectSearchRoute": True, "expectProductResults": False, "expectedBodyContains": ""},
        {**m("SCH-004", "Empty search — may stay on home or show search with no criteria", "P2", "boundary-value", "regression", "system-test", "OWASP", OWASP_INPUT),
         "query": "", "expectSearchRoute": False, "expectProductResults": False, "expectedBodyContains": ""},
        {**m("SCH-ST-01", "Ardışık arama durum geçişi iMac then HTC", "P1", "state-transition", "regression", "system-test", "ISTQB"),
         "query": "iMac", "secondQuery": "HTC", "expectSearchRoute": True, "expectProductResults": True,
         "expectedBodyContains": "iMac", "secondExpectedBodyContains": "HTC"},
        {**m("SCH-SEC-01", "SQL injection in search query", "P0", "security", "regression", "system-test", "OWASP", OWASP_INPUT),
         "query": "' OR 1=1--", "expectSearchRoute": True, "expectProductResults": False, "expectedBodyContains": ""},
        {**m("SCH-SEC-02", "XSS payload in search query", "P1", "security", "regression", "system-test", "OWASP", OWASP_XSS),
         "query": "<script>alert(1)</script>", "expectSearchRoute": True, "expectProductResults": False, "expectedBodyContains": ""},
        {**m("SCH-BV-01", "Single character search query", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "query": "i", "expectSearchRoute": True, "expectProductResults": True, "expectedBodyContains": ""},
        {**m("SCH-BV-02", "Long search query (100 chars)", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "query": "a" * 100, "expectSearchRoute": True, "expectProductResults": False, "expectedBodyContains": ""},
        {**m("SCH-EP-01", "Lowercase imac case-insensitive partition", "P2", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "query": "imac", "expectSearchRoute": True, "expectProductResults": True, "expectedBodyContains": "imac"},
        {**m("SCH-EP-02", "Partial keyword Mac returns Mac products", "P2", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "query": "Mac", "expectSearchRoute": True, "expectProductResults": True, "expectedBodyContains": "Mac"},
        {**m("SCH-NEG-01", "Special characters only search", "P1", "negative-test", "regression", "system-test", "ISTQB"),
         "query": "!@#$%", "expectSearchRoute": True, "expectProductResults": False, "expectedBodyContains": ""},
        {**m("SCH-EG-01", "Typo search Imac still finds iMac", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "query": "Imac", "expectSearchRoute": True, "expectProductResults": True, "expectedBodyContains": "iMac"},
        {**m("SCH-EG-02", "Numeric-only search query", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "query": "12345", "expectSearchRoute": True, "expectProductResults": False, "expectedBodyContains": ""},
        {**m("SCH-ST-02", "Search iMac then empty second query", "P2", "state-transition", "regression", "system-test", "ISTQB"),
         "query": "iMac", "secondQuery": "", "expectSearchRoute": True, "expectProductResults": True,
         "expectedBodyContains": "iMac", "secondExpectedBodyContains": ""},
        {**m("SCH-SEC-03", "HTML entity encoded XSS attempt", "P2", "security", "regression", "system-test", "OWASP", OWASP_XSS),
         "query": "&lt;script&gt;alert(1)&lt;/script&gt;", "expectSearchRoute": True, "expectProductResults": False, "expectedBodyContains": ""},
        {**m("SCH-BV-03", "Whitespace-only search query", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "query": "   ", "expectSearchRoute": False, "expectProductResults": False, "expectedBodyContains": ""},
        {**m("SCH-EP-03", "Brand search Canon returns camera products", "P2", "equivalence-partitioning", "regression", "system-test", "ISTQB"),
         "query": "Canon", "expectSearchRoute": True, "expectProductResults": True, "expectedBodyContains": "Canon"},
    ]

    wishlist = [
        {**m("WLS-001", "Add visible home product to wish list and verify page", "P0", "state-transition", "smoke", "acceptance-test", "ISTQB"),
         "productNameContains": "iMac", "expectedAlertContains": "wish", "expectedWishListPageContains": "iMac"},
        {**m("WLS-002", "Second product family from home grid", "P1", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "productNameContains": "HTC", "expectedAlertContains": "wish", "expectedWishListPageContains": "HTC"},
        {**m("WLS-NEG-01", "Giriş yapmadan wishlist route'una erişim", "P1", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "guestWishlistAccess": True, "productNameContains": "", "expectedAlertContains": "", "expectedWishListPageContains": ""},
        {**m("WLS-NEG-02", "Var olmayan ürünü wishlist'e ekleme", "P1", "negative-test", "regression", "system-test", "ISTQB"),
         "expectWishlistAddFailure": True, "productNameContains": "zzzznonexistentproduct999",
         "expectedAlertContains": "", "expectedWishListPageContains": ""},
        {**m("WLS-BV-01", "Aynı ürünü 2 kez wishlist'e ekleme", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "wishlistAddRepeatCount": 2, "productNameContains": "iMac", "expectedAlertContains": "wish", "expectedWishListPageContains": "iMac"},
        {**m("WLS-003", "Add MacBook to wish list", "P1", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "productNameContains": "MacBook", "expectedAlertContains": "wish", "expectedWishListPageContains": "MacBook"},
        {**m("WLS-004", "Add Canon to wish list", "P2", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "productNameContains": "Canon", "expectedAlertContains": "wish", "expectedWishListPageContains": "Canon"},
        {**m("WLS-BV-02", "Same product added 3 times boundary", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "wishlistAddRepeatCount": 3, "productNameContains": "HTC", "expectedAlertContains": "wish", "expectedWishListPageContains": "HTC"},
        {**m("WLS-SEC-01", "XSS-like product name should not add to wishlist", "P1", "security", "regression", "system-test", "OWASP", OWASP_XSS),
         "expectWishlistAddFailure": True, "productNameContains": "<script>alert(1)</script>",
         "expectedAlertContains": "", "expectedWishListPageContains": ""},
        {**m("WLS-SEC-02", "SQL injection-like product fragment", "P2", "security", "regression", "system-test", "OWASP", OWASP_INPUT),
         "expectWishlistAddFailure": True, "productNameContains": "' OR 1=1--",
         "expectedAlertContains": "", "expectedWishListPageContains": ""},
        {**m("WLS-NEG-03", "Empty product name fragment", "P1", "negative-test", "regression", "system-test", "ISTQB"),
         "expectWishlistAddFailure": True, "productNameContains": "", "expectedAlertContains": "", "expectedWishListPageContains": ""},
        {**m("WLS-EG-01", "Typo product name fails wishlist add", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "expectWishlistAddFailure": True, "productNameContains": "ImacTypo999", "expectedAlertContains": "", "expectedWishListPageContains": ""},
        {**m("WLS-ST-01", "Add Samsung to wish list state transition", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "productNameContains": "Samsung", "expectedAlertContains": "wish", "expectedWishListPageContains": "Samsung"},
        {**m("WLS-ST-02", "Add Palm to wish list state transition", "P2", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "productNameContains": "Palm", "expectedAlertContains": "wish", "expectedWishListPageContains": "Palm"},
        {**m("WLS-EP-01", "Partial Mac matches Mac products", "P2", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "productNameContains": "Mac", "expectedAlertContains": "wish", "expectedWishListPageContains": "Mac"},
        {**m("WLS-EG-02", "Special chars product search fails", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "expectWishlistAddFailure": True, "productNameContains": "!@#$%", "expectedAlertContains": "", "expectedWishListPageContains": ""},
        {**m("WLS-NEG-04", "Numeric-only product fragment fails", "P2", "negative-test", "regression", "system-test", "ISTQB"),
         "expectWishlistAddFailure": True, "productNameContains": "99999", "expectedAlertContains": "", "expectedWishListPageContains": ""},
        {**m("WLS-BV-03", "Single repeat count explicit boundary", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "wishlistAddRepeatCount": 1, "productNameContains": "iPhone", "expectedAlertContains": "wish", "expectedWishListPageContains": "iPhone"},
    ]

    newsletter = [
        {**m("NWS-001", "Subscribe newsletter = Yes", "P0", "state-transition", "smoke", "acceptance-test", "ISTQB"),
         "subscribe": True, "expectedSuccessContains": "success"},
        {**m("NWS-002", "Subscribe newsletter = No", "P0", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "subscribe": False, "expectedSuccessContains": "success"},
        {**m("NWS-NEG-01", "Newsletter sayfasına login olmadan erişim", "P1", "negative-test", "regression", "system-test", "OWASP", OWASP_AUTH),
         "subscribe": False, "expectedSuccessContains": "login"},
        {**m("NWS-BV-01", "Abonelik durumu arka arkaya 2 kez değiştirme", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "toggleSubscriptionTwice": True, "subscribe": True, "expectedSuccessContains": "success"},
        {**m("NWS-003", "Toggle twice starting from No subscription", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "toggleSubscriptionTwice": True, "subscribe": False, "expectedSuccessContains": "success"},
        {**m("NWS-EP-01", "Subscribe Yes equivalence partition", "P1", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "subscribe": True, "expectedSuccessContains": "success"},
        {**m("NWS-EP-02", "Subscribe No equivalence partition", "P1", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "subscribe": False, "expectedSuccessContains": "success"},
        {**m("NWS-ST-01", "Yes then verify newsletter page state", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "subscribe": True, "expectedSuccessContains": "newsletter"},
        {**m("NWS-ST-02", "No then verify newsletter page state", "P2", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "subscribe": False, "expectedSuccessContains": "newsletter"},
        {**m("NWS-BV-02", "Triple toggle boundary via double toggle pattern", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "toggleSubscriptionTwice": True, "subscribe": True, "expectedSuccessContains": ""},
        {**m("NWS-NEG-02", "Guest access via unauthenticatedAccess flag", "P1", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "unauthenticatedAccess": True, "subscribe": False, "expectedSuccessContains": "login"},
        {**m("NWS-SEC-01", "Auth bypass attempt on newsletter route", "P1", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "unauthenticatedAccess": True, "subscribe": True, "expectedSuccessContains": "login"},
        {**m("NWS-EG-01", "Re-subscribe Yes after No (user error recovery)", "P2", "error-guessing", "regression", "acceptance-test", "ISTQB"),
         "toggleSubscriptionTwice": True, "subscribe": False, "expectedSuccessContains": "success"},
        {**m("NWS-EG-02", "Subscribe Yes twice via toggle pattern", "P2", "error-guessing", "regression", "acceptance-test", "ISTQB"),
         "toggleSubscriptionTwice": True, "subscribe": True, "expectedSuccessContains": "success"},
        {**m("NWS-NEG-03", "Negative guest redirect expects login body", "P2", "negative-test", "regression", "system-test", "OWASP", OWASP_AUTH),
         "unauthenticatedAccess": True, "subscribe": False, "expectedSuccessContains": "returning customer"},
        {**m("NWS-ST-03", "Subscribe Yes state persistence check", "P2", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "subscribe": True, "expectedSuccessContains": "success"},
        {**m("NWS-ST-04", "Subscribe No state persistence check", "P2", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "subscribe": False, "expectedSuccessContains": "success"},
        {**m("NWS-BV-03", "Boundary: toggle with subscribe true baseline", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "toggleSubscriptionTwice": True, "subscribe": True, "expectedSuccessContains": "newsletter"},
    ]

    my_account = [
        {**m("MAC-001", "Logged-in user sees account dashboard", "P0", "state-transition", "smoke", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "", "expectedUrlContains": "route=account/account", "expectedBodyContains": "My Account"},
        {**m("MAC-002", "Open Address Book from account menu", "P0", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Address Book", "expectedUrlContains": "address", "expectedBodyContains": "Address"},
        {**m("MAC-003", "Open Order History from account menu", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Order History", "expectedUrlContains": "order", "expectedBodyContains": "Order"},
        {**m("MAC-004", "Open Wish List from account sidebar", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Wish List", "expectedUrlContains": "wishlist", "expectedBodyContains": ""},
        {**m("MAC-005", "Open Downloads from account sidebar", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Downloads", "expectedUrlContains": "download", "expectedBodyContains": ""},
        {**m("MAC-006", "Open Recurring payments from account sidebar", "P2", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Recurring payments", "expectedUrlContains": "recurring", "expectedBodyContains": ""},
        {**m("MAC-007", "Open Reward Points from account sidebar", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Reward Points", "expectedUrlContains": "reward", "expectedBodyContains": ""},
        {**m("MAC-008", "Open Returns from account sidebar", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Returns", "expectedUrlContains": "return", "expectedBodyContains": ""},
        {**m("MAC-009", "Open Transactions from account sidebar", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Transactions", "expectedUrlContains": "transaction", "expectedBodyContains": ""},
        {**m("MAC-010", "Open Newsletter from account sidebar", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Newsletter", "expectedUrlContains": "newsletter", "expectedBodyContains": ""},
        {**m("MAC-011", "Open Logout from account sidebar", "P2", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Logout", "expectedUrlContains": "logout", "expectedBodyContains": ""},
        {**m("MAC-NEG-02", "Boş sidebar ile gezinme yapılmamalı", "P1", "negative-test", "regression", "system-test", "ISTQB"),
         "sidebarLinkText": "", "expectedUrlContains": "route=account/account", "expectedBodyContains": "My Account"},
        {**m("MAC-NEG-03", "Geçersiz route ile hesap sayfasına erişim", "P1", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "sidebarLinkText": "", "invalidRouteUrl": "https://ecommerce-playground.lambdatest.io/index.php?route=account/nonexistent_route_xyz",
         "expectedUrlContains": "ecommerce-playground", "expectedBodyContains": ""},
        {**m("MAC-BV-01", "Sidebar'da geçersiz link metnine tıklama", "P1", "boundary-value", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "", "expectedUrlContains": "account", "expectedBodyContains": ""},
        {**m("MAC-012", "Open Edit Account Information from sidebar", "P0", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Edit Account Information", "expectedUrlContains": "edit", "expectedBodyContains": "First Name"},
        {**m("MAC-013", "Open Change Password from sidebar", "P1", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "sidebarLinkText": "Change Password", "expectedUrlContains": "password", "expectedBodyContains": "Password"},
        {**m("MAC-SEC-01", "Invalid route with SQL injection attempt", "P1", "security", "regression", "system-test", "OWASP", OWASP_AUTH),
         "sidebarLinkText": "", "invalidRouteUrl": "https://ecommerce-playground.lambdatest.io/index.php?route=account/account' OR '1'='1",
         "expectedUrlContains": "ecommerce-playground", "expectedBodyContains": ""},
        {**m("MAC-EG-01", "User-typed invalid account URL (error guessing)", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "sidebarLinkText": "", "invalidRouteUrl": "https://ecommerce-playground.lambdatest.io/index.php?route=account/typo_user_mistake",
         "expectedUrlContains": "ecommerce-playground", "expectedBodyContains": ""},
    ]

    settings = [
        {**m("MAC-SET-01", "Edit your account information (name / phone)", "P0", "state-transition", "smoke", "acceptance-test", "ISTQB"),
         "flow": "edit-information", "firstName": "Edited", "lastName": "Customer", "telephone": "+15550001111"},
        {**m("MAC-SET-02", "Address form validation: country must be selected", "P0", "negative-test", "regression", "acceptance-test", "OWASP", OWASP_INPUT),
         "flow": "address-book", "addressFirstName": "Addr", "addressLastName": "One", "addressLine1": "100 Test Street",
         "city": "Istanbul", "postcode": "34000", "expectSuccess": False, "expectedMessageContains": "please select"},
        {**m("MAC-SET-04", "Successful address book entry with valid data", "P0", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "flow": "address-book", "addressFirstName": "Addr", "addressLastName": "Two", "addressLine1": "200 Test Avenue",
         "city": "Ankara", "postcode": "06000", "expectSuccess": True, "expectedMessageContains": ""},
        {**m("MAC-NEG-01", "Edit info with empty first name", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "flow": "edit-information", "firstName": "", "lastName": "Customer", "telephone": "+15550001111",
         "expectSuccess": False, "expectedMessageContains": "First Name"},
        {**m("MAC-SET-NEG-02", "Profil güncellemede telefon alanına harf yazma", "P1", "negative-test", "regression", "system-test", "ISTQB"),
         "flow": "edit-information", "firstName": "Edited", "lastName": "Customer", "telephone": "abcNotDigits", "expectSuccess": True},
        {**m("MAC-SET-NEG-03", "Empty last name on profile edit", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "flow": "edit-information", "firstName": "Edited", "lastName": "", "telephone": "+15550001111",
         "expectSuccess": False, "expectedMessageContains": "Last Name"},
        {**m("MAC-SET-NEG-04", "Empty address line on address book", "P1", "boundary-value", "regression", "system-test", "ISTQB"),
         "flow": "address-book", "addressFirstName": "Addr", "addressLastName": "One", "addressLine1": "",
         "city": "Istanbul", "postcode": "34000", "expectSuccess": False, "expectedMessageContains": "Address"},
        {**m("MAC-SET-NEG-05", "Empty city on address book", "P2", "boundary-value", "regression", "system-test", "ISTQB"),
         "flow": "address-book", "addressFirstName": "Addr", "addressLastName": "One", "addressLine1": "100 Test Street",
         "city": "", "postcode": "34000", "expectSuccess": False, "expectedMessageContains": "City"},
        {**m("MAC-SET-SEC-01", "XSS payload in profile first name", "P1", "security", "regression", "system-test", "OWASP", OWASP_XSS),
         "flow": "edit-information", "firstName": "<script>alert(1)</script>", "lastName": "Customer", "telephone": "+15550001111", "expectSuccess": True},
        {**m("MAC-SET-SEC-02", "SQL injection in address line field", "P2", "security", "regression", "system-test", "OWASP", OWASP_INPUT),
         "flow": "address-book", "addressFirstName": "Addr", "addressLastName": "One", "addressLine1": "'; DROP TABLE addresses;--",
         "city": "Istanbul", "postcode": "34000", "expectSuccess": True, "expectedMessageContains": ""},
        {**m("MAC-SET-NEG-01", "Şifre değiştirirken mevcut şifre yanlış", "P1", "negative-test", "regression", "system-test", "OWASP", OWASP_AUTH),
         "flow": "change-password", "currentPasswordOverride": "WrongCurrentPass!", "newPassword": "Test5678!", "confirmNewPassword": "Test5678!", "expectSuccess": True},
        {**m("MAC-SET-NEG-06", "New password and confirm mismatch", "P1", "negative-test", "regression", "system-test", "OWASP", OWASP_AUTH),
         "flow": "change-password", "newPassword": "Test5678!", "confirmNewPassword": "MismatchPass!", "expectSuccess": False, "expectedMessageContains": "Password"},
        {**m("MAC-SET-NEG-07", "Empty new password on change password", "P1", "boundary-value", "regression", "system-test", "OWASP", OWASP_AUTH),
         "flow": "change-password", "newPassword": "", "confirmNewPassword": "", "expectSuccess": False, "expectedMessageContains": "Password"},
        {**m("MAC-SET-EG-01", "Weak new password (too short)", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "flow": "change-password", "newPassword": "123", "confirmNewPassword": "123", "expectSuccess": False, "expectedMessageContains": "Password"},
        {**m("MAC-SET-EG-02", "Telephone with spaces only", "P2", "error-guessing", "regression", "system-test", "ISTQB"),
         "flow": "edit-information", "firstName": "Edited", "lastName": "Customer", "telephone": "   ", "expectSuccess": True},
        {**m("MAC-SET-EP-01", "Valid profile update equivalence partition", "P1", "equivalence-partitioning", "regression", "acceptance-test", "ISTQB"),
         "flow": "edit-information", "firstName": "Valid", "lastName": "User", "telephone": "+15551234567", "expectSuccess": True},
        {**m("MAC-SET-03", "Change your password (must be last — updates session password)", "P0", "state-transition", "regression", "acceptance-test", "OWASP", OWASP_AUTH),
         "flow": "change-password", "newPassword": "Test5678!", "confirmNewPassword": "Test5678!"},
        {**m("MAC-SET-ST-01", "Profile edit then verify account area reachable", "P2", "state-transition", "regression", "acceptance-test", "ISTQB"),
         "flow": "edit-information", "firstName": "State", "lastName": "Test", "telephone": "+15559998888", "expectSuccess": True},
    ]

    all_files = {
        "login-scenarios.json": login,
        "register-scenarios.json": register,
        "forgot-password-scenarios.json": forgot,
        "cart-scenarios.json": cart,
        "checkout-scenarios.json": checkout,
        "search-scenarios.json": search,
        "wishlist-scenarios.json": wishlist,
        "newsletter-scenarios.json": newsletter,
        "my-account-scenarios.json": my_account,
        "my-account-settings-scenarios.json": settings,
    }

    total = 0
    for name, data in all_files.items():
        write(name, data)
        total += len(data)
    print(f"TOTAL: {total} scenarios")


if __name__ == "__main__":
    main()
